- name: Firewalld / Ensure Firewalld is installed
  ansible.builtin.dnf:
    name: firewalld
    state: present
  become: yes
  register: firewalld_installed

- name: Firewalld / Start Service, if it was just installed
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: yes
  become: yes
  when: firewalld_installed.changed