- name: Terraform / Preload OS images
  ansible.builtin.get_url:
    name: "/var/lib/libvirt/images/{{ item.name }}"
    url: "{{ item.url }}"
    state: present
  loop: "{{ lang_terraform_libvirt_images }}"

