---
- import_tasks: vars.yaml
  tags:
    - app_terraform
    - app_terraform:check
    - app_terraform:install
- import_tasks: check.yaml
  tags:
    - app_terraform
    - app_terraform:check
    - app_terraform:install
- import_tasks: terraform.yaml
  tags:
    - app_terraform
    - app_terraform:install
