---
- name: Repo / Terraform
  ansible.builtin.yum_repository:
    name: terraform
    description: Hashicorp Terraform Repo
    baseurl: https://rpm.releases.hashicorp.com/{{ hashicorp_release }}/{{ hashicorp_release_version | default("$releasever") }}/$basearch/stable
    gpgkey: https://rpm.releases.hashicorp.com/gpg
    gpgcheck: yes
  become: yes

- name: Terraform / Install binary
  ansible.builtin.yum:
    name:
      - terraform
    state: present
  become: yes

